### ISSUE TITLE
Top Searched Models

### ISSUE THREAD

**Issue by ferenckerekes** [kulcsarrudolf/sp-search#20]
<img width="435" alt="Screenshot 2023-03-08 at 23 04 38" src="https://user-images.githubusercontent.com/33689521/223851431-e5780483-9475-439e-8e85-9f29c7b55799.png">

**Comment by ferenckerekes** [comment]
Listed top searched models not active, i can`t select any models from top searched models.

**Comment by kulcsarrudolf** [comment]
This is weird. I noticed that, too. I will take a 👁️ on it.
